# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
