# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(max_length=254, upload_to='images_store')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Store')),
            ],
        ),
    ]
